-- InventoryLink Credit (Utang) subsystem migration
-- Safe to run multiple times.

ALTER TABLE public.stores
ADD COLUMN IF NOT EXISTS debt_grace_period_days integer DEFAULT 30;

CREATE TABLE IF NOT EXISTS public.customer_credit_accounts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id bigint NOT NULL,
    customer_name text NOT NULL,
    contact_info text DEFAULT 'Not Provided'::text,
    outstanding_balance numeric DEFAULT 0.00 CHECK (outstanding_balance >= 0::numeric),
    credit_limit numeric DEFAULT 2000.00,
    oldest_unpaid_credit_date timestamp with time zone,
    last_payment_date timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.customer_credit_accounts
ADD COLUMN IF NOT EXISTS telegram_id bigint,
ADD COLUMN IF NOT EXISTS customer_name text,
ADD COLUMN IF NOT EXISTS contact_info text DEFAULT 'Not Provided'::text,
ADD COLUMN IF NOT EXISTS outstanding_balance numeric DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS credit_limit numeric DEFAULT 2000.00,
ADD COLUMN IF NOT EXISTS oldest_unpaid_credit_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS last_payment_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS public.credit_transaction_ledger (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL,
    transaction_type text NOT NULL,
    amount numeric NOT NULL CHECK (amount > 0::numeric),
    reference_notes text,
    logged_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.credit_transaction_ledger
ADD COLUMN IF NOT EXISTS account_id integer,
ADD COLUMN IF NOT EXISTS transaction_type text,
ADD COLUMN IF NOT EXISTS amount numeric,
ADD COLUMN IF NOT EXISTS reference_notes text,
ADD COLUMN IF NOT EXISTS logged_at timestamp with time zone DEFAULT now();

DO $$
DECLARE
    fk_delete_rule "char";
BEGIN
    SELECT c.confdeltype
    INTO fk_delete_rule
    FROM pg_constraint c
    WHERE c.conname = 'customer_credit_accounts_telegram_id_fkey'
      AND c.conrelid = 'public.customer_credit_accounts'::regclass;

    IF fk_delete_rule IS NULL THEN
        ALTER TABLE public.customer_credit_accounts
        ADD CONSTRAINT customer_credit_accounts_telegram_id_fkey
        FOREIGN KEY (telegram_id)
        REFERENCES public.stores(telegram_id)
        ON DELETE CASCADE;
    ELSIF fk_delete_rule <> 'c' THEN
        ALTER TABLE public.customer_credit_accounts
        DROP CONSTRAINT customer_credit_accounts_telegram_id_fkey;

        ALTER TABLE public.customer_credit_accounts
        ADD CONSTRAINT customer_credit_accounts_telegram_id_fkey
        FOREIGN KEY (telegram_id)
        REFERENCES public.stores(telegram_id)
        ON DELETE CASCADE;
    END IF;
END $$;

DO $$
DECLARE
    fk_delete_rule "char";
BEGIN
    SELECT c.confdeltype
    INTO fk_delete_rule
    FROM pg_constraint c
    WHERE c.conname = 'credit_transaction_ledger_account_id_fkey'
      AND c.conrelid = 'public.credit_transaction_ledger'::regclass;

    IF fk_delete_rule IS NULL THEN
        ALTER TABLE public.credit_transaction_ledger
        ADD CONSTRAINT credit_transaction_ledger_account_id_fkey
        FOREIGN KEY (account_id)
        REFERENCES public.customer_credit_accounts(id)
        ON DELETE CASCADE;
    ELSIF fk_delete_rule <> 'c' THEN
        ALTER TABLE public.credit_transaction_ledger
        DROP CONSTRAINT credit_transaction_ledger_account_id_fkey;

        ALTER TABLE public.credit_transaction_ledger
        ADD CONSTRAINT credit_transaction_ledger_account_id_fkey
        FOREIGN KEY (account_id)
        REFERENCES public.customer_credit_accounts(id)
        ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'unique_tenant_customer'
    ) THEN
        ALTER TABLE public.customer_credit_accounts
        ADD CONSTRAINT unique_tenant_customer UNIQUE (telegram_id, customer_name);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'credit_transaction_ledger_transaction_type_check'
    ) THEN
        ALTER TABLE public.credit_transaction_ledger
        ADD CONSTRAINT credit_transaction_ledger_transaction_type_check
        CHECK (transaction_type IN ('CREDIT_ISSUED', 'PAYMENT_RECEIVED'));
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'customer_credit_accounts_outstanding_balance_check'
    ) THEN
        ALTER TABLE public.customer_credit_accounts
        ADD CONSTRAINT customer_credit_accounts_outstanding_balance_check
        CHECK (outstanding_balance >= 0::numeric);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'credit_transaction_ledger_amount_check'
    ) THEN
        ALTER TABLE public.credit_transaction_ledger
        ADD CONSTRAINT credit_transaction_ledger_amount_check
        CHECK (amount > 0::numeric);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_credit_accounts_tenant
ON public.customer_credit_accounts(telegram_id);

CREATE INDEX IF NOT EXISTS idx_credit_ledger_account
ON public.credit_transaction_ledger(account_id);

CREATE OR REPLACE FUNCTION public.increment_debt(account_id_input integer, amount_input numeric)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public.customer_credit_accounts
    SET outstanding_balance = outstanding_balance + amount_input
    WHERE id = account_id_input;
END;
$$;
